### ISSUE TITLE
Vehicle Spawn Request

### ISSUE THREAD

**Issue by hardkopy** [MaximiliumM/appearancemenumod#6]
I hope this is the right place, I'm getting a bit old in the tooth so not always fully with it :) ere a few vehicles I'd like to see in APP.
1' Panam's Thornton Colby Truck
2' The nomad motorcycle with pannier bags front and rare (sorry do not know the name)
3' Denny's Villefort Aderado Convetible (Denny was a part of Johnny Silvers Samurai band)

Functions x2
1' Ability to add current vehicle to garage ( so if you brake into, commandeer a vehicle you just a press a key while in the driver seat to add it to your garage)
2' Fix vehicle and Auto Fix loop, by pressing a key (currently  part  of Str8tup Menu mod)

Thank you

**Comment by MaximiliumM** [comment]
1) Panam's vehicle is in already.
2) It'll be a little hard without knowing the name. Maybe if you find it yourself and give me an appearance name.
3) Will try to find it and add it.

About functions:

1) As far as I know, the game doesn't allow to add random stuff with code to the garage. Only player vehicles. People has succeeded in adding random vehicles to the garage by altering files in the game's archive. If we ever find a way to do that, I'll definitely have it as an option. Meanwhile, you can use the Save Appearance function, because most vehicles in the game are player vehicles with different appearances.

2) Sorry, I'll discuss this with Daz to see his opinion as well, but I'm not keen on adding that to the mod simply because it's not in the scope of the mod.

**Comment by MaximiliumM** [comment]
Closing issue. If you want to discuss it further, come to our Discord channel: https://discord.gg/ubhsM58r
